config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :lists, only: [:new, :create, :index]
  end

  resources :lists do
    resources :tasks do
      resources :blockers
      member do
        patch :complete
      end
    end
  end

  root 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :owner, class_name:"User", foreign_key:"user_id"
  belongs_to :user
  # has_many :task
  # has_many :users, :through => :tasks
  has_many :tasks

  has_many :collaborations
  has_many :collaboration_users, through: :collaborations, :source => :user
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show

  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      byebug
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :description)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lists</h1>

<% @lists.each do |list| %>
  <div class="index_row clearfix">
    <h4 class="list_title"><%= link_to list.name, list %></h4>
    <p class="list_sub_title"><%= list.description %></p>
  </div>
<% end %>

<div class="links">
  <%= link_to "New List", new_list_path %>
</div>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p><strong>Name:</strong><%= @list.name %></p>

<p><strong>Description:</strong><%= @list.description %></p>

<%= link_to 'Edit', edit_list_path(@list) %> | <%= link_to 'Back', lists_path %>

<h4 class="list_name"><%= @list.name %></h4>
<p class="list_sub_title"><%= @list.description %></p>

<div id="task_wrapper">
  <%= render "tasks/form" %>
 	<%= render @list.tasks %>
</div>

<div class="links">
	<%= link_to 'Edit', edit_list_path(@list) %> |
	<%= link_to 'Delete', list_path(@list), method: :delete, data: { confirm: "Are you sure?" }
 %> |
  <%= link_to 'Back', lists_path %>
</div>