config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :lists, only: [:new, :create, :index]
  end

  resources :lists do
    resources :tasks do
      resources :blockers
      member do
        patch :complete
      end
    end
  end

  root 'lists#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  belongs_to :user
  has_many :blockers, class_name: "Task", foreign_key: "parent_task_id"

  def completed?
  	!completed_at.blank?
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, except: [:create]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = @list.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit

  end

  def complete
		@task.update_attribute(:completed_at, Time.now)
		redirect_to @list, notice: "Todo item completed"
	end

  # POST /tasks
  # POST /tasks.json
  def create
    # byebug
    @list = List.find(params[:list_id])
    @task = @list.tasks.build(task_params)
    # byebug
    if !task_params[:user_id]
      # current user
      @user = User.find(1)
      @task.update(user_id:@user.id)
    end
    respond_to do |format|
      if @task.save
        format.html { redirect_to @list, notice: 'Task was successfully created.' }
        format.json
      else
        format.html { render :new }
        format.json
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    if @task.destroy
			flash[:success] = "Todo List item was deleted."
		else
			flash[:error] = "Todo List item could not be deleted."
		end
		redirect_to @todo_list

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_list
    #
		#   @list = List.find(params[:list_id])
	  # end

    def set_task
      @task = @list.tasks.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:detail, :list_id, :user_id,)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for([@list, @list.tasks.build]) do |f| %>
  <div class="input-field center-align">
	  <%= f.text_field :detail, placeholder: "New Task" %>
  </div>
	<%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<div class="row clearfix">
	<% if task %>
	<% if task.completed? %>
			<div class="col s8 task">
					<p style="opacity: 0.4;"><strike><%= task.detail %></strike></p>
					<p style="opacity: 0.5;" class="time-created-at item-sub-title">Created <%= task.created_at %> ago</p>
			</div>
			<div class="col s1 complete">
				<%= link_to complete_list_task_path(@list, task.id), method: :patch do %>
					<i class="material-icons">spellcheck</i>
				<% end %>
			</div>
			<div class="col s1 trash">
				<%= link_to list_task_path(@list, task.id), method: :delete, data: { confirm: "Are you sure?" } do %>
					<i class="material-icons">delete</i>
				<% end %>
			</div>

	<% else %>
			<div class="col s8 task">
				<p style="opacity: 0.4;"><%= task.detail %></p>
				<p style="opacity: 0.5;" class="time-created-at item-sub-title">Created <%= task.created_at %> ago</p>
			</div>
			<div class="col s1 complete">
				<%= link_to complete_list_task_path(@list, task.id), method: :patch do %>
					<i class="material-icons">spellcheck</i>
				<% end %>
			</div>
			<div class="col s1 trash">
				<%= link_to list_task_path(@list, task.id), method: :delete, data: { confirm: "Are you sure?" } do %>
					<i class="material-icons">delete</i>
				<% end %>
			</div>
		<% end %>
		<% end %>
	</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collaboration.tasks.each do |task| %>
      <tr>
        <td><%= task.detail %></td>
        <td><%#= link_to 'Show', collaboration_task_path %></td>
        <td><%#= link_to 'Edit', edit_collaboration_task_path(task) %></td>
        <td><%#= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_collaboration_task_path(@collaboration) %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', list_tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @task.detail %>
  <%= link_to "add blocker", new_task_blocker_path(@task) %>
</p>
<ul>
  <% @task.blockers.each do |blocker| %>
  <li><%= blocker.id %><%= blocker.detail %></li>
  <% end %>
</ul>
<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>